version: "3.4"
services:
  mongo:
    image: mongo:5.0.2
    ports:
        - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
